version: 0.1

log:
  level: info
  fields:
    service: registry

storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ["*"]
    Access-Control-Allow-Methods: ["GET, POST, OPTIONS, DELETE, HEAD"]
    Access-Control-Allow-Credentials: ["true"]
    Access-Control-Allow-Headers: ["Authorization", "Accept", "Cache-Control"]
    Access-Control-Max-Age: [1728000]
    Access-Control-Expose-Headers: ["Docker-Content-Digest"]

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

auth:
  htpasswd:
    realm: basic-realm
    path: /htpasswd
